services:
  frontend:
    build:
      context: ../node_modules/@acamae/frontend
    env_file:
      - ../.env.${NODE_ENV:-production}
    ports:
      - '${FRONTEND_PORT:-80}:80'
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: ../node_modules/@acamae/backend
    env_file:
      - ../.env.${NODE_ENV:-production}
    ports:
      - '${BACKEND_PORT:-4000}:4000'
    depends_on:
      - db
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: mysql:8.0
    env_file:
      - ../.env.${NODE_ENV:-production}
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '${DB_PORT:-3306}:3306'
    networks:
      - app-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
